#!/usr/bin/python3

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist

def _5mvt():
    rclpy.init()
    aNode = Node("mouv5")
    talker = ROSTalker(aNode)
    rclpy.spin(aNode)
    aNode.destroy_node()
    rclpy.shutdown()

class ROSTalker:
    def __init__(self, rosNode):
        self._publisher = rosNode.create_publisher(Twist, '/multi/cmd_nav', 10)
        self._timer = rosNode.create_timer(0.5, self.timer_callback)

    def timer_callback(self):
        velocity = Twist()
        velocity.linear = [0.5, 0, 0]
        velocity.angular = [0, 0, 1.0]
        self._publisher.publish(velocity)

if __name__ == "__main__":
    _5mvt()